### ISSUE TITLE
Ruleset pull_request requires parameters sub-dict

### ISSUE THREAD

**Issue by BowlesCR** [natescherer/postmodern-repo-copiertemplate#221]
Hi there! o/

Came across your repo looking for examples of how to mass-create rulesets with githubkit and get the fiddly payload right. 

I noticed that pull_requests settings weren't being correctly applied for me and worked out that the settings need to be wrapped in a parameters sub-dict. As-is it silently ignores these settings and you'll find that the UI doesn't show your desired state.

https://github.com/natescherer/postmodern-repo-copiertemplate/blob/main/template/tasks.py#L160

**Comment by natescherer** [comment]
@BowlesCR Hey, thanks for calling this out! Glad my code was helpful, the ruleset API is kind of a mess to figure out.
